name = "jetson-orin-nano"
description = "Red Hat Device Edge for the Jetson Orin Nano"
version = "0.0.1"
modules = []

# Group: Headless Management
#  Description: Tools for managing the system without an attached graphical console.
#  Mandatory Packages:
#    PackageKit
#    cockpit-bridge
#    cockpit-packagekit
#    cockpit-podman
#    cockpit-storaged
#    cockpit-system
#    cockpit-ws
#    openssh-server
#  Default Packages:
#    sscg
[[groups]]
name = "Headless Management"

# Group: Container Management
#  Description: Tools for managing Linux containers
#  Mandatory Packages:
#    buildah
#    containernetworking-plugins
#    podman
#  Optional Packages:
#    python3-psutil
#    toolbox
[[groups]]
name = "Container Management"

##
## Nvidia Packages
##
[[packages]]
name =  "kernel"
# Hardcode the kernel version needed by the Nvidia Kernel module.
# Any mismatch prevent the ostree from being built.
version = "5.14.0-362.13.1.el9_3"

[[packages]]
name =  "nvidia-jetpack-core"
version = "*"

[[packages]]
name = "nvidia-jetpack-kmod-firmware"
version = "*"

[[packages]]
name = "nvidia-jetpack-v4l"
version = "*"

[[packages]]
name = "nvidia-jetpack-kmod-modprobe"
version = "*"

[[packages]]
name = "nvidia-jetpack-kmod"
version = "*"

[[packages]]
name = "nvidia-container-toolkit-base"
version = "*"

##
## Misc.
##
[[packages]]
name = "subscription-manager-plugin-ostree"
version = "*"

[[packages]]
name = "greenboot-rpm-ostree-grub2"
version = "*"

##
## Microshift
##

[[packages]]
name = "microshift"
version = "*"

[customizations]
hostname = "train-controller.local"

[customizations.services]
enabled = ["cockpit.socket", "sshd", "microshift"]

[customizations.timezone]
timezone = "Europe/Paris"
ntpservers = ["0.fr.pool.ntp.org", "1.fr.pool.ntp.org"]

[customizations.locale]
languages = ["fr_FR.UTF-8"]
keyboard = "fr"

[customizations.firewall]
ports = ["22:tcp", "30000:tcp", "9090:tcp", "6443:tcp"]
